apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aggregator-rolebinding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: aggregator-service-account  # ServiceAccount name
    namespace: monitoring
roleRef:
  kind: Role
  name: aggregator-role  # Role name
  apiGroup: rbac.authorization.k8s.io